version: '3.8'

services:
  postgres:
    image: postgres:18.2-alpine3.22
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pastebin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:4.2.0
    container_name: pastebin-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # имя сервиса Docker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    
      # Настройки для разработки (один реплика)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - pastebin-network
    depends_on:
      postgres:
        condition: service_healthy

  pastebin-microservice:
    build: ./pastebinMicroservice
    container_name: pastebin-microservice
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paste_db
      SPRING_DATASOURCE_USERNAME: paste_db_user
      SPRING_DATASOURCE_PASSWORD: d7a29
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CREATE_PASTE_TOPIC: create-pasteRequest-topic
      SPRING_KAFKA_GET_HASH_TOPIC: get-hash-topic
      SPRING_KAFKA_GENERATED_HASH_TOPIC: generated-hash-topic
    networks:
      - pastebin-network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  hash-microservice:
    build: ./hashMicroservice
    container_name: hash-microservice
    ports:
      - "8091:8091"
    environment:
      SERVER_PORT: 8091
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hash_db
      SPRING_DATASOURCE_USERNAME: hash_db_user
      SPRING_DATASOURCE_PASSWORD: vcaa21
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CREATE_PASTE_TOPIC: create-paste-topic
      SPRING_KAFKA_GET_HASH_TOPIC: get-hash-topic
      SPRING_KAFKA_GENERATED_HASH_TOPIC: generated-hash-topic
    networks:
      - pastebin-network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  web-front:
    build: ./front
    container_name: pastebin-web
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PASTE_SERVICE_URL: http://pastebin-microservice:8090
    networks:
      - pastebin-network
    depends_on:
      - pastebin-microservice

networks:
  pastebin-network:
    driver: bridge

volumes:
  postgres_data: