spring.application.name=hashMicroservice

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.create_paste_topic_name=${SPRING_KAFKA_CREATE_PASTE_TOPIC}
spring.kafka.get_hash_topic_name=${SPRING_KAFKA_GET_HASH_TOPIC}
spring.kafka.generated_hash_topic_name=${SPRING_KAFKA_GENERATED_HASH_TOPIC}

hash.length = 8

server.port = ${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
